name: 'mae_gdl'
real_losses:
  - _target_: deep_tree.models.components.loss.PixelLossWrapper
    loss_fn:
      _target_: deep_tree.models.components.loss.PatchAvgLoss
    name: "mae_avg"
    weight: 1
  - _target_: deep_tree.models.components.loss.PixelLossWrapper
    loss_fn:
      _target_: deep_tree.models.components.loss.GradientDifferenceLoss
      reduction: "mean"
    name: "gdl"
    weight: 0.25
#  - _target_: deep_tree.models.components.loss.PixelLossWrapper
#    loss_fn:
#      _target_: deep_tree.models.components.loss.FFTMagnitudeLoss
#      reduction: "mean"
#    name: "fft"
#    weight: 0.01
