name: 'pmae_wgdl_bce'
real_losses:
  - _target_: deep_tree.models.components.loss.PixelLossWrapper
    loss_fn:
      _target_: torch.nn.L1Loss
      reduction: "mean"
    name: "mae"
    weight: 1
#  - _target_: deep_tree.models.components.loss.PixelLossWrapper
#    loss_fn:
#      _target_: deep_tree.models.components.loss.WeightedGradientDifferenceLoss
#      reduction: "mean"
#    name: "wgdl"
#    weight: 0.25
  - _target_: deep_tree.models.components.loss.ClassifMetricWrapper
    loss_fn:
      _target_: torch.nn.BCEWithLogitsLoss
    name: "bce"
    weight: 1