validation_metrics:
  - _target_: deep_tree.models.components.loss.PixelLossWrapper
    loss_fn:
      _target_: deep_tree.models.components.loss.RMSELoss
      reduction: "mean"
    name: "rmse"
    weight: 1

test_metrics:
  - _target_: deep_tree.models.components.loss.PixelLossWrapper
    loss_fn:
      _target_: deep_tree.models.components.loss.RMSELoss
      reduction: "mean"
    name: "rmse"
    weight: 1
